/**
 * pnpm's own commands, which take no script lookup when they follow `pnpm`.
 *
 * `test`, `start` and `build` are deliberately absent: pnpm treats them as
 * script shorthands, so a citation of them is a script citation and must
 * resolve against `package.json` like any other.
 *
 * @packageDocumentation
 */
export const PNPM_BUILTINS: ReadonlySet<string> = new Set([
  'add',
  'approve-builds',
  'audit',
  'bin',
  'cat-file',
  'cat-index',
  'catalog',
  'completion',
  'config',
  'create',
  'dedupe',
  'deploy',
  'dlx',
  'doctor',
  'env',
  'exec',
  'fetch',
  'find-hash',
  'help',
  'i',
  'ignored-builds',
  'import',
  'info',
  'init',
  'install',
  'install-test',
  'it',
  'licenses',
  'link',
  'list',
  'ls',
  'outdated',
  'pack',
  'patch',
  'patch-commit',
  'patch-remove',
  'prune',
  'publish',
  'rb',
  'rebuild',
  'remove',
  'rm',
  'root',
  'search',
  'self-update',
  'server',
  'setup',
  'store',
  'uninstall',
  'unlink',
  'up',
  'update',
  'version',
  'view',
  'why',
]);
