import { defineConfig, devices } from "@playwright/test";

import { getFreePort } from "./scripts/free-port";
import { acceptStamp, stampFor } from "./scripts/port-handshake";

/**
 * Playwright configuration for E2E tests.
 *
 * The default project runs against a production build served by `pnpm start`
 * on a port probed free at config load, so two checkouts running the suite at
 * once on one host each prove their own build; nothing shares a fixed port
 * and no existing server is ever reused (testing-strategy §Harnesses Adapt to
 * Shared Hosts). The port is assigned here, in the harness's composition
 * root, and nowhere else: tests and helpers take Playwright's `baseURL` and
 * request fixtures. The build is run by Playwright's web server so every test
 * exercises the same artefact a visitor would see in production. This
 * eliminates dev-only flakes — the Turbopack `Runtime ChunkLoadError` overlay
 * and the Next.js dev-tools issue badge — at the source.
 *
 * Playwright evaluates this file in the runner and again in every worker
 * process, so the runner's probed port has to reach its workers or each would
 * probe its own and connect to nothing. The runner stamps the port into its
 * own environment as `<port>:<runner pid>`; the runner accepts only its own
 * stamp and a worker only its parent's (`scripts/port-handshake.ts`), so a
 * value set from outside the harness, even by the runner's own parent, is
 * ignored and the process probes as if it were absent. The environment is
 * the runner's handshake to its children, never configuration. The probe
 * releases the port before the server binds it, so a taker in between is
 * possible: `reuseExistingServer: false` then fails the run loudly instead
 * of proving a server this run did not start.
 *
 * The PDF is generated by the `pnpm build` script, so PDF
 * tests no longer need a separate project; they run alongside everything else.
 *
 * Scripts:
 * - `pnpm test:e2e` — run the full E2E suite against the production build
 * - `pnpm test:ui` — open Playwright UI mode
 *
 * @see https://playwright.dev/docs/test-configuration
 */

const HANDSHAKE = "PLAYWRIGHT_SITE_PORT_HANDSHAKE";

const port =
  acceptStamp(process.env[HANDSHAKE], {
    pid: process.pid,
    ppid: process.ppid,
    isWorker: process.env.TEST_WORKER_INDEX !== undefined,
  }) ?? (await getFreePort());
process.env[HANDSHAKE] = stampFor(port, process.pid);
const baseURL = `http://localhost:${port}`;

export default defineConfig({
  testDir: "e2e",
  fullyParallel: true,
  forbidOnly: Boolean(process.env.CI),
  retries: 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: process.env.CI ? "list" : "html",
  use: {
    baseURL,
    trace: "on-first-retry",
  },

  projects: [
    {
      name: "default",
      use: { ...devices["Desktop Chrome"] },
    },
  ],

  webServer: {
    command: `pnpm build && pnpm start --port ${port}`,
    url: baseURL,
    // The site derives its own public URL from PORT locally (lib/site-config.ts),
    // so the build and the server it produces carry the probed origin in their
    // canonical URLs and JSON-LD, as the PDF generator already arranges for the
    // server it starts.
    env: { PORT: String(port) },
    reuseExistingServer: false,
    timeout: 120_000,
  },
});
