import { defineConfig, devices } from "@playwright/test";

import { getFreePort } from "./scripts/free-port";
import { acceptStamp, stampFor } from "./scripts/port-handshake";

/**
 * Playwright configuration for E2E tests.
 *
 * The default project runs against a production build served by `pnpm start`
 * on a port probed free at config load, so two checkouts running the suite at
 * once on one host each prove their own build; nothing shares a fixed port
 * and no existing server is ever reused (testing-strategy §Harnesses Adapt to
 * Shared Hosts). The port is assigned here, in the harness's composition
 * root, and nowhere else: tests and helpers take Playwright's `baseURL` and
 * request fixtures. The build is run by Playwright's web server so every test
 * exercises the same artefact a visitor would see in production. This
 * eliminates dev-only flakes — the Turbopack `Runtime ChunkLoadError` overlay
 * and the Next.js dev-tools issue badge — at the source.
 *
 * Playwright evaluates this file in the runner and again in every process it
 * forks from the runner (its workers, and the loader that UI mode and the
 * test server use), so the runner's probed port has to reach them or each
 * would probe its own and connect to nothing. The runner stamps the port into
 * its own environment as `<port>:<runner pid>`; the runner accepts only its
 * own stamp and a forked child only its parent's (`scripts/port-handshake.ts`).
 * A forked child is known by Node's own IPC-channel state, which Node sets at
 * startup from a variable it consumes and removes from the environment, so
 * the distinction never travels by inheritance: a stamp inherited from the
 * environment, even one carrying the runner's parent pid, is inert and the
 * process probes as if it were absent, and a process that accepts its
 * parent's stamp leaves it untouched, so nothing forked further down accepts
 * a stamp from anywhere but the runner. The guarantee is against accidental
 * inheritance, not an adversary: a parent that forks this runner itself, or
 * sets Node's channel variable deliberately, can seed a stamp and could as
 * easily edit this file. The environment carries the runner's handshake to
 * its children and never the port or origin; `CI` is read below for the
 * runner's own settings.
 *
 * Playwright treats the first server that answers the web server URL as the
 * one it started, so the harness owns its port for as long as any other
 * prober could be handed it: `scripts/e2e-web-server.ts` binds the probed
 * port with a 503 responder for the whole build (whose PDF generator probes a
 * port of its own, and on a Linux runner was handed this one) and starts Next
 * on it only after. The two hand-offs, probe to bind and listener to Next,
 * run with no build in flight, so no prober exists to take the port, and a
 * port taken anyway fails the bind loudly. `reuseExistingServer: false` keeps
 * a server this run did not start from ever counting as its own.
 *
 * The PDF is generated by the `pnpm build` script, so PDF
 * tests no longer need a separate project; they run alongside everything else.
 *
 * Scripts:
 * - `pnpm test:e2e` — run the full E2E suite against the production build
 * - `pnpm test:ui` — open Playwright UI mode
 *
 * @see https://playwright.dev/docs/test-configuration
 */

const HANDSHAKE = "PLAYWRIGHT_SITE_PORT_HANDSHAKE";

const accepted = acceptStamp(process.env[HANDSHAKE], {
  pid: process.pid,
  ppid: process.ppid,
  // Node's IPC-channel state: set in the workers and loader Playwright forks, absent in a
  // runner spawned by pnpm or turbo.
  isWorker: process.send !== undefined,
});
const port = accepted ?? (await getFreePort());
if (accepted === undefined) {
  // Only a process that probed stamps; one that accepted its parent's stamp keeps it.
  process.env[HANDSHAKE] = stampFor(port, process.pid);
}
const baseURL = `http://localhost:${port}`;

export default defineConfig({
  testDir: "e2e",
  fullyParallel: true,
  forbidOnly: Boolean(process.env.CI),
  retries: 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: process.env.CI ? "list" : "html",
  use: {
    baseURL,
    trace: "on-first-retry",
  },

  projects: [
    {
      name: "default",
      use: { ...devices["Desktop Chrome"] },
    },
  ],

  webServer: {
    // The server script holds the port through the build, then serves on it.
    command: "pnpm e2e:server",
    url: baseURL,
    // PORT carries the probed port to the server script, and the site derives its
    // own public URL from it locally (lib/site-config.ts), so the build and the
    // server it produces carry the probed origin in their canonical URLs and
    // JSON-LD, as the PDF generator already arranges for the server it starts.
    env: { PORT: String(port) },
    reuseExistingServer: false,
    timeout: 120_000,
  },
});
